server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      filter:
        commons-log:
          statement-executable-sql-log-enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    user: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    inetutils:
      ignored-interfaces:
        - .*VMware
  elasticsearch:
    uris:
      [ "127.0.0.1:9200"]
logging:
  level:
    com.hpj.admin.modules.sys.mapper: debug
xh:
  test:
    - a
    - b
    - c