server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    inetutils:
      ignored-interfaces:
        - .*VMware
  elasticsearch:
    uris:
      [ "127.0.0.1:9200"]
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com.hpj.admin.modules.sys.mapper: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: '/**'
      packages-to-scan: com.hpj.admin.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    configuration-factory: java.lang.Object