server:
  port: 8090
spring:
  kafka:
    bootstrap-servers: 192.168.0.107:9092
  application:
    name: admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      filter:
        commons-log:
          statement-executable-sql-log-enable: true
logging:
  level:
    com.hpj.admin.modules.sys.mapper: debug
mybatis-plus:
  type-enums-package: com.hpj.admin.enums